/**
 * API module for agent-fw studio.
 */

export type {
  StudioBridgeCapability,
  StudioCapabilities,
  StudioRuntimeKind,
} from "~/lib/domain/studio-capabilities";
// Client configuration and base functions
export {
  type ApiConfig,
  type ApiError,
  type ApiErrorCode,
  apiFetch,
  del,
  get,
  getApiConfig,
  patch,
  post,
  put,
  setApiConfig,
  setWorkspaceHeader,
} from "./client";
// Data API operations (sources, discovery, profiling, knowledge, search, tools, metrics, import, admin)
export {
  addKnowledge,
  browseKnowledge,
  cancelImport,
  cancelProfiling,
  connectImportStream,
  createDataSource,
  createMetric,
  deleteDataSource,
  deleteDocument,
  deleteKnowledgeItem,
  deleteMetric,
  estimateProfilingCost,
  executeTool,
  extractKnowledge,
  findJoinPath,
  getAdminStatus,
  getDataReadiness,
  getDataSource,
  getDocument,
  getImportStatus,
  getKnowledgeItem,
  getMetric,
  getProfilingStatus,
  getTableColumns,
  getTableDetail,
  type ImportStreamHandlers,
  type IngestionStreamHandlers,
  ingestDocuments,
  ingestKnowledgeFromSource,
  type KnowledgeIngestHandlers,
  listDataSources,
  listDocuments,
  listMetrics,
  listSchemas,
  listTables,
  listTools,
  purgeDatabase,
  resolveTerm,
  runMigrations,
  sampleTable,
  startImport,
  startProfileDatabase,
  startProfileTable,
  testConnection,
  unifiedSearch,
  updateDataSource,
  updateKnowledgeItem,
  updateMetric,
} from "./data";
// Eval operations
export {
  cancelEval,
  compareEvalRuns,
  connectEvalStream,
  createEvalCreateBody,
  createEvalFork,
  deleteEvalFork,
  deleteEvalRun,
  type EvalCapabilities,
  type EvalCapabilityMode,
  type EvalStreamHandlers,
  expandEval,
  exportEvalFailures,
  getEvalRun,
  listEvalCapabilities,
  listEvalForks,
  listEvalRuns,
  listTestCaseSets,
  pauseEval,
  type RunComparisonSummary,
  rerunEvalCases,
  resumeEval,
  startEvalStream,
  type TestCaseComparison,
  uploadTestCaseSet,
} from "./evals";
// Generic JSON SSE helpers
export {
  type JsonSSEHandlers,
  startJsonSSEStream,
  type TerminalCheck,
} from "./sse";
// SSE connection state machine (programs-as-values)
export {
  advanceSequence,
  createSSEConnection,
  type SSEConnection,
  type SSEConnectionConfig,
  type SSEConnectionStatus,
  type SSEStatusDetail,
} from "./sse-connection";
// SSE streaming for chat
export {
  type ChatRequest,
  type ChatRequestMessage,
  createChatRequest,
  type StreamHandlers,
  startChatStream,
} from "./streaming";
// Studio-specific operations
export {
  getModelConfig,
  getProjectConfig,
  getStudioStatus,
  type ModelConfig,
  type Preset,
  type ProjectConfig,
  type ProjectRoleConfig,
  type ProjectRoleResponseContract,
  type ProjectTopologyRole,
  type RuntimeStatus,
  type StudioStatus,
} from "./studio";
// Test case operations
export {
  type BatchResult,
  batchTestCases,
  clearTestCaseBuilderSession,
  createFromChat,
  createTestCase,
  deleteTestCase,
  getTestCase,
  getTestCaseBuilderSession,
  getThreadTrace,
  getToolCatalog,
  type ListTestCasesParams,
  listTestCases,
  rebuildTestCaseIndex,
  saveFromBuilder,
  updateTestCase,
  type ValidationIssue,
  type ValidationResult,
  validateTestCase,
} from "./tests";
// Thread CRUD operations
export {
  type BackendMessage,
  createThread,
  deleteThread,
  type FetchMessagesResult,
  fetchMessagesWithFormat,
  fetchSubAgentMessages,
  forkThread,
  getFileDownloadUrl,
  getLatestThreadRunReport,
  getSubAgentResponse,
  getThread,
  getThreadMessages,
  listThreadFiles,
  listThreads,
  type ThreadFile,
  type ThreadRunLatency,
  type ThreadRunReport,
  type ThreadRunSubAgent,
  type ThreadRunToolCall,
  type ThreadRunUsage,
  type UIMessage,
  type UIMessagePart,
  updateThread,
} from "./threads";
// Workspace CRUD operations
export {
  createWorkspace,
  deleteWorkspace,
  getWorkspace,
  listWorkspaces,
  updateWorkspace,
} from "./workspaces";
