//! Shared tool names and descriptions for catalog tool adapters.
//!
//! Agent-facing descriptions live here so runtime prompt rendering and
//! `ToolHandler::definition()` cannot drift.

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct CatalogToolMetadata {
    pub name: &'static str,
    pub description: &'static str,
}

pub const SEARCH_CATALOG: CatalogToolMetadata = CatalogToolMetadata {
    name: "search_catalog",
    description: concat!(
        "/**\n",
        " * Discover candidate catalog entities from search text.\n",
        " *\n",
        " * Use this when:\n",
        " * - You need to find relevant tables, columns, enum values, metrics, knowledge, documents, or relationships from a phrase such as `table_name`, `column_name`, `metric_name`, or `schema.table_name`.\n",
        " * - You are starting a catalog workflow and do not yet know the exact catalog ids or qualified names to inspect.\n",
        " * - You need facets or suggested filters to narrow a broad domain term before hydrating details.\n",
        " *\n",
        " * Do not use this when:\n",
        " * - You already have selected ids or qualified names and need canonical details; use get_catalog_entities.\n",
        " * - You need table columns, data types, keys, or profiling summaries; use list_schema_fields after selecting table refs.\n",
        " * - You need joins, adjacent graph context, or semantic-rule scope; use get_catalog_relations or get_relation_paths_between after selecting refs.\n",
        " * - You are ready to run SQL; use execute_query only after targeted hydration confirms the query context.\n",
        " *\n",
        " * Inputs:\n",
        " * - query: Natural-language search phrase or identifier. Required string. Examples: `table_name`, `column_name`, `metric_name`, `schema.table_name`, `literal_value`.\n",
        " * - kinds: Optional array of entity kinds to search. Values include `table`, `column`, `relationship`, `enum_value`, `metric`, `knowledge`, `document`, and `data_quality_finding`. Omit to search all public kinds.\n",
        " * - filters: Optional structured filters applied during search. Supports database_id, schema, table, column, data_type, semantic_type, tags, knowledge_type, relation/source/target fields, preferred_query_surface, and low_cardinality_enum.\n",
        " * - limit: Optional requested result count, 1..=50. The runtime may clamp broad requests lower.\n",
        " * - cursor: Optional opaque cursor from a prior search_catalog call with the same logical query.\n",
        " *\n",
        " * Behavior:\n",
        " * - Runs lexical catalog search through the runtime catalog search backend in the current tenant/workspace scope.\n",
        " * - Hydrates candidate ids internally only to drop stale hits and shape compact result envelopes.\n",
        " * - Does not mutate catalog data, target database rows, or workspace state.\n",
        " * - Does not return complete schema, joins, or executable query context.\n",
        " *\n",
        " * Returns:\n",
        " * - query: Normalized query string used for search.\n",
        " * - results: Ranked candidate CatalogEntity values with ids, names, compact details, tags, match diagnostics, and warnings. Treat these as candidates, not final query context.\n",
        " * - facets and suggested_filters: Counts and filter hints for narrowing follow-up discovery.\n",
        " * - filter_resolution: Canonical applied filters plus unresolved or ambiguous filters.\n",
        " * - pagination: returned, limit, has_more, and optional next_cursor.\n",
        " * - diagnostics: Runtime search details such as backend, candidate_count, hydrated_count, and round_trips. Do not branch on backend names.\n",
        " *\n",
        " * After calling:\n",
        " * - Select only the relevant refs, then call get_catalog_entities for canonical details, list_schema_fields for table columns, or relation/path tools for joins and semantic-rule context.\n",
        " * - Do not treat broad search results as executable SQL context; hydrate selected refs and verify fields, joins, filters, and semantic rules before execute_query.\n",
        " */"
    ),
};

pub const GET_CATALOG_ENTITIES: CatalogToolMetadata = CatalogToolMetadata {
    name: "get_catalog_entities",
    description: concat!(
        "/**\n",
        " * Hydrate selected catalog refs into canonical typed entities.\n",
        " *\n",
        " * Use this when:\n",
        " * - Use after search_catalog with selected ids or qualified names when you need authoritative typed details.\n",
        " * - You need provenance, relation refs, metric definitions, knowledge/document body context, enum metadata, or data-quality details for specific entities.\n",
        " * - You already narrowed broad discovery and want the next level of detail for a small, explicit ref set.\n",
        " *\n",
        " * Do not use this when:\n",
        " * - You need broad discovery from a phrase; use search_catalog first.\n",
        " * - You need table column lists or field profiles; use list_schema_fields for table columns.\n",
        " * - You need graph adjacency or join paths; use get_catalog_relations or get_relation_paths_between.\n",
        " *\n",
        " * Inputs:\n",
        " * - refs: Required array of 1..=50 CatalogRef objects. Prefer `id` values returned by prior catalog tools. Use `qualified_name` such as `schema.table_name` when ids are not known. Use `name` with `kind` only when necessary to disambiguate.\n",
        " *\n",
        " * Behavior:\n",
        " * - Resolves refs exactly through the scoped catalog, preserving requested order where possible.\n",
        " * - Batch-hydrates catalog entries and assembles runtime-selected entity details.\n",
        " * - May hydrate document or knowledge body text from the configured KV payload store.\n",
        " * - Does not search broadly, inspect all table fields, execute SQL, or mutate state.\n",
        " *\n",
        " * Returns:\n",
        " * - entities: Hydrated CatalogEntity values. Small ref sets may use verbose details; larger sets may use summary details.\n",
        " * - missing: Input refs that could not be resolved or disappeared before hydration.\n",
        " * - warnings: Non-fatal metadata, ambiguity, or payload hydration issues.\n",
        " *\n",
        " * After calling:\n",
        " * - Use list_schema_fields for selected table/query-surface columns, get_catalog_relations for adjacent context, or get_relation_paths_between for joins before execute_query.\n",
        " * - Treat missing or warning entries as uncertainty to resolve before SQL planning.\n",
        " */"
    ),
};

pub const LIST_SCHEMA_FIELDS: CatalogToolMetadata = CatalogToolMetadata {
    name: "list_schema_fields",
    description: concat!(
        "/**\n",
        " * List columns and field metadata for selected tables or query surfaces.\n",
        " *\n",
        " * Use this when:\n",
        " * - Use after selecting table or query-surface refs to inspect fields before execute_query.\n",
        " * - You need column names, data types, nullability, keys, enum hints, semantic types, or profiling summaries.\n",
        " * - You need to verify that projected SQL columns actually exist in the selected table or preferred query surface.\n",
        " *\n",
        " * Do not use this when:\n",
        " * - You have not discovered or selected table refs yet; use search_catalog first.\n",
        " * - You need high-level entity details, provenance, or knowledge/document bodies; use get_catalog_entities.\n",
        " * - You need joins or graph paths; use get_catalog_relations or get_relation_paths_between.\n",
        " *\n",
        " * Inputs:\n",
        " * - tables: Required array of 1..=10 CatalogRef objects for table or query-surface entities. Prefer ids from search_catalog or get_catalog_entities.\n",
        " * - filters: Optional field filters such as column, data_type, semantic_type, tags, low_cardinality_enum, or related table filters.\n",
        " * - limit_per_table: Optional requested field count per table, 1..=200. The runtime may clamp or paginate large schemas.\n",
        " *\n",
        " * Behavior:\n",
        " * - Resolves each table ref exactly, validates that it is a table/query surface, then reads catalog column entities linked to it.\n",
        " * - Applies field filters after ref/filter resolution.\n",
        " * - Does not sample target data, execute SQL, search broadly, or mutate state.\n",
        " *\n",
        " * Returns:\n",
        " * - tables: One result per resolved table, including the table entity, field CatalogEntity values, pagination, and table-level warnings.\n",
        " * - filter_resolution: Applied and unresolved field filters.\n",
        " * - warnings: Request-level non-fatal issues.\n",
        " *\n",
        " * After calling:\n",
        " * - Use the returned field names and types to plan SQL projections, filters, grouping, and joins.\n",
        " * - If joins or semantic rules are still unclear, call get_catalog_relations or get_relation_paths_between before execute_query.\n",
        " */"
    ),
};

pub const GET_CATALOG_RELATIONS: CatalogToolMetadata = CatalogToolMetadata {
    name: "get_catalog_relations",
    description: concat!(
        "/**\n",
        " * Fetch adjacent catalog graph relations for selected refs.\n",
        " *\n",
        " * Use this when:\n",
        " * - You have selected entity refs and need neighboring tables, columns, enum values, metrics, knowledge, or relationship vertices.\n",
        " * - You need to understand semantic-rule scope, metric dependencies, enum values for a column, or direct relationship context.\n",
        " * - Missing information is catalog context, not target database rows.\n",
        " *\n",
        " * Do not use this when:\n",
        " * - You need initial discovery from a phrase; use search_catalog first.\n",
        " * - You need full paths between two known endpoints; use get_relation_paths_between.\n",
        " * - You need table fields only; use list_schema_fields.\n",
        " * - You are ready to run SQL with complete context; use execute_query.\n",
        " *\n",
        " * Inputs:\n",
        " * - refs: Required array of 1..=20 CatalogRef objects whose adjacent graph relations should be returned.\n",
        " * - direction: Optional relation direction relative to each input ref: `outgoing`, `incoming`, or `both`. Use `both` for context discovery.\n",
        " * - relation_kinds: Optional relation kind strings such as `has_column`, `references_table`, `enum_value_of`, `applies_to`, `metric_uses`, `synonym_of`, or `equivalent_to`.\n",
        " * - target_kinds: Optional array of target entity kinds to return.\n",
        " * - limit_per_ref: Optional requested related-entity count per ref, 1..=100.\n",
        " *\n",
        " * Behavior:\n",
        " * - Resolves each source ref exactly, traverses catalog links/relations in the requested direction, hydrates targets, and applies relation/target filters.\n",
        " * - Does not execute SQL, sample target rows, or mutate catalog state.\n",
        " *\n",
        " * Returns:\n",
        " * - results: One result per source with the source entity, adjacent relation edges, target entities, pagination, and warnings.\n",
        " * - relation edges include relation_kind, direction, target, optional description, and optional relationship vertex details.\n",
        " * - warnings: Non-fatal missing-target, truncation, or filter issues.\n",
        " *\n",
        " * After calling:\n",
        " * - Use adjacent targets to choose the next hydration or schema-inspection step.\n",
        " * - For SQL joins between endpoints, call get_relation_paths_between or verify join fields before execute_query.\n",
        " */"
    ),
};

pub const GET_RELATION_PATHS_BETWEEN: CatalogToolMetadata = CatalogToolMetadata {
    name: "get_relation_paths_between",
    description: concat!(
        "/**\n",
        " * Find join or semantic graph paths between selected catalog refs.\n",
        " *\n",
        " * Use this when:\n",
        " * - You already have source and target refs and need to connect them for SQL planning or semantic explanation.\n",
        " * - You need join hops between tables or query surfaces before writing SQL.\n",
        " * - You need to trace how knowledge, metrics, or semantic rules reach concrete tables and columns.\n",
        " *\n",
        " * Do not use this when:\n",
        " * - You have not discovered endpoints yet; use search_catalog first.\n",
        " * - You only need adjacent one-hop context; use get_catalog_relations.\n",
        " * - You only need fields for one table; use list_schema_fields.\n",
        " *\n",
        " * Inputs:\n",
        " * - from: Required CatalogRef for the source endpoint.\n",
        " * - to: Required array of 1..=20 CatalogRef target endpoints.\n",
        " * - path_type: Optional path family: `join` for SQL join paths, `semantic` for graph/semantic context, or `any` to try both.\n",
        " * - max_depth: Optional maximum semantic graph depth, 1..=6.\n",
        " *\n",
        " * Behavior:\n",
        " * - Resolves endpoints exactly, then searches catalog join metadata and/or semantic graph edges within the requested depth.\n",
        " * - For `any`, attempts join paths first and falls back to semantic paths when no join path is found.\n",
        " * - Does not execute SQL, sample rows, or mutate state.\n",
        " *\n",
        " * Returns:\n",
        " * - paths: One path result per target with from_entity, to, found, path_type, steps, length, and warnings.\n",
        " * - steps may include via_relation details and join metadata such as from_column, to_column, and join_type.\n",
        " * - found=false means no path was found within limits; warnings may indicate truncation or unresolved endpoints.\n",
        " *\n",
        " * After calling:\n",
        " * - Use found join steps to build SQL joins, then verify required fields with list_schema_fields before execute_query.\n",
        " * - If no path is found, do not invent joins; search or hydrate additional refs instead.\n",
        " */"
    ),
};

pub const SAMPLE_TABLE_DATA: CatalogToolMetadata = CatalogToolMetadata {
    name: "sample_table_data",
    description: concat!(
        "/**\n",
        " * Fetch a small exploratory sample from a selected table or query surface.\n",
        " *\n",
        " * Use this when:\n",
        " * - You already selected and inspected a table/query surface and need representative values or row shape.\n",
        " * - You need to understand examples for filters, enum-like values, formatting, or data quality before final SQL.\n",
        " *\n",
        " * Do not use this when:\n",
        " * - You need final analysis or aggregation; use execute_query after planning.\n",
        " * - You need schema, keys, or field metadata; use list_schema_fields.\n",
        " * - You need joins or semantic-rule context; use relation/path tools.\n",
        " * - You have not selected a table/query surface yet; use search_catalog first.\n",
        " *\n",
        " * Inputs:\n",
        " * - table: Required CatalogRef for a table or query-surface entity. Prefer an id from catalog tools.\n",
        " * - columns: Optional array of column names to include. Omit to sample runtime-approved/catalog-known columns.\n",
        " * - limit: Optional requested sample row count, 1..=20.\n",
        " *\n",
        " * Behavior:\n",
        " * - Resolves and validates the table ref through the catalog, validates requested columns against catalog fields, then reads a small sample from the target database.\n",
        " * - Read-only against target data. Does not mutate catalog state or target rows.\n",
        " * - Projects returned rows to catalog-known/requested columns and may warn when target rows contain columns missing from the catalog.\n",
        " *\n",
        " * Returns:\n",
        " * - table: The resolved table CatalogEntity.\n",
        " * - columns: Returned column names.\n",
        " * - rows: Sample row objects, capped by limit.\n",
        " * - row_count: Number of rows returned.\n",
        " * - sample_note and warnings: Non-fatal sampling or catalog freshness notes.\n",
        " *\n",
        " * After calling:\n",
        " * - Use samples only as exploratory evidence for values and shape.\n",
        " * - Use execute_query for final calculations only after schema, joins, filters, and semantic rules are confirmed.\n",
        " */"
    ),
};

pub const EXECUTE_QUERY: CatalogToolMetadata = CatalogToolMetadata {
    name: "execute_query",
    description: concat!(
        "/**\n",
        " * Run a validated read-only SQL query as the final step.\n",
        " *\n",
        " * Use this when:\n",
        " * - You have already completed catalog discovery and targeted hydration.\n",
        " * - You have finished confirming tables, fields, joins, filters, and semantic rules with catalog tools.\n",
        " * - The user needs actual target database rows, aggregates, or final analysis.\n",
        " *\n",
        " * Do not use this when:\n",
        " * - You only have broad search_catalog candidates or uncertain table/field choices.\n",
        " * - You still need schema details; use list_schema_fields.\n",
        " * - You still need joins, relationship context, metrics, or semantic rules; use get_catalog_entities, get_catalog_relations, or get_relation_paths_between.\n",
        " * - You need representative examples but not final analysis; use sample_table_data.\n",
        " *\n",
        " * Inputs:\n",
        " * - sql: Required single read-only SELECT or WITH query. Mutations, DDL, multi-statement SQL, and unsafe clauses are rejected. Use catalog-confirmed table and column names.\n",
        " * - params: Optional positional bind parameters for user-provided values where possible.\n",
        " * - limit: Optional requested output row limit, 1..=1000. The runtime enforces or wraps limits and may clamp large requests.\n",
        " * - purpose: Optional short audit/trace explanation of why this query is being run.\n",
        " *\n",
        " * Behavior:\n",
        " * - Parses and validates SQL as read-only SELECT/WITH, rejects mutations and DDL, applies/enforces row limits, and executes against the target database.\n",
        " * - Reads target database data. Does not mutate target rows or catalog state.\n",
        " *\n",
        " * Returns:\n",
        " * - columns: Output column names.\n",
        " * - rows: Returned row objects.\n",
        " * - row_count: Number of rows returned.\n",
        " * - truncated: Whether the runtime stopped before all possible rows because of limits.\n",
        " * - warnings: Non-fatal validation, limit, or execution notes.\n",
        " *\n",
        " * After calling:\n",
        " * - Use returned rows to answer the user, noting truncation or warnings.\n",
        " * - If the query fails due to missing context, return to catalog hydration/schema/relation tools rather than guessing names or joins.\n",
        " */"
    ),
};

pub const SURFACE_TOOLS: [CatalogToolMetadata; 7] = [
    SEARCH_CATALOG,
    GET_CATALOG_ENTITIES,
    LIST_SCHEMA_FIELDS,
    GET_CATALOG_RELATIONS,
    GET_RELATION_PATHS_BETWEEN,
    SAMPLE_TABLE_DATA,
    EXECUTE_QUERY,
];
